# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(max_length=1000, verbose_name='备注')),
                ('control_cp_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.ControlCpUrl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cmc_logs',
                'verbose_name': '日志管理中心',
                'verbose_name_plural': '日志管理中心',
            },
        ),
    ]
