# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='control_cp_url',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cmdb.ControlCpUrl'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
