# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(max_length=1000, verbose_name='备注')),
            ],
            options={
                'db_table': 'cmc_cp',
                'verbose_name': 'CP管理',
                'verbose_name_plural': 'CP管理',
            },
        ),
        migrations.CreateModel(
            name='ControlCpUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('in_url', models.CharField(max_length=255, verbose_name='接入URI')),
                ('out_url', models.CharField(max_length=255, verbose_name='接出URI')),
                ('remark', models.TextField(max_length=1000, verbose_name='备注')),
            ],
            options={
                'db_table': 'cmc_cp_url',
                'verbose_name': '配置CP地址',
                'verbose_name_plural': '配置CP地址',
            },
        ),
    ]
